### ISSUE TITLE
OTAA failed to Join

### ISSUE THREAD

**Issue by hhazime** [houluy/lora-motes-emulator#10]
Hello, 

I am trying to use to send data to test the ChirpStack integration from my backend. 

I am not able to receive a Join Accept from ChirpStack, the join request packet is received to the ChirpStack side. All the session keys are being generated, I checked them inside the node dashboard.  

i am using LoraWan 1.0.2, any suggesstions?

**Comment by houluy** [comment]
Hi,

Try to run `python main.py pull` before any other commands to register gateway to ChirpStack first.

Besides, we have push some new codes to fix bugs, please try the version of latest commit. : )

**Comment by hhazime** [comment]
Hello,

Thank you for taking the time to reply.

When i try to pull i am getting the following reply
`
PS C:\Users\husse\Desktop\lora-motes-emulator-master> python main.py pull
2021-12-03 11:45:56,840 - INFO - PULL DATA -
Version: 02, Token: 8fd1, Identifier: 02, GatewayEUI: 4e7b2799b9bfd427


2021-12-03 11:45:56,994 - ERROR - Parsing PULL_ACK message error, 
predefined format: <s2ss8s,
received data: 028fd104
`

**Comment by Xiao-Di** [comment]
Hi,
Our previous version was coded related to the LoRa Protacol, in which the PULL ACK was defined as a 12-byte message including a 8-byte gatewayEUI.
However, when we tested it with Chirpstack, it turned out the Chirpstack Server sended back a 4-byte PULL ACK without gatewayEUI. So we adjusted our emulator accordingly.
Try to clone our latest version and give it another try. :)

**Comment by hhazime** [comment]
Hello @Xiao-Di 
I tried the following:

1.  python main.py pull 
Reply: 
````
2021-12-03 12:55:16,406 - INFO - PULL DATA -
Version: 02, Token: 0ddd, Identifier: 02, GatewayEUI: 21cb13cc7a380a3e


2021-12-03 12:55:16,553 - INFO - PULL ACK -
Version: 02, Token: 0ddd, Identifier: 04,`
````
2. python main.py join -n
Reply:
````
2021-12-03 12:56:21,298 - INFO - Forming a join request message - 
NwkKey: fe6d154c31a646f585b75d5682f7b67f, AppKey: fe6d154c31a646f585b75d5682f7b67f, AppEUI: b098c295f6a98191, DevEUI: b098c295f6a98191, DevNonce: 9e76, MIC: bf1e3186,Final Join Req: 009181a9f695c298b09181a9f695c298b09e76bf1e3186 --


2021-12-03 12:56:21,299 - INFO - Sending a PUSH DATA -
Verson: 02, Token: 6129, Identifier: 00, GatewayEUI: 21cb13cc7a380a3e


2021-12-03 12:56:21,450 - INFO - Receiving a PUSH ACK -
Version: 02, Token: 6129, Identifier: 01


2021-12-03 12:56:21,664 - INFO - Receiving a PULL RESP - 
Version: 02, Token: b7ee, Identifier: 03 --


2021-12-03 12:56:21,665 - INFO - -----Parsing a join acpt message - 
devaddr: 00f4ac39, joinnonce: 000015, homenetid: 000000, optneg: 0, rx1droffset: 0, rx2dr: 0, Calculated MIC: 597c217b --


2021-12-03 12:56:21,666 - INFO - Join Accept (MIC verified) -
Original data: 15000000000039acf4000001287684f87d84c88584184f84e8568400
MHDR: 20,Join type: ff,DevAddr: 00f4ac39, OptNeg: 0, CFList: 287684f87d84c88584184f84e8568400,
````
3.  python main.py app -m helloworld 
Reply:
````
2021-12-03 12:57:26,012 - INFO - Uplink application data -
MHDR: 80, FHDR: 39acf400000000, FOpts: , FPort: 20, FRMPayload (after encryption): e6d9b8f323a7c70e7959, MIC: 924240e2 --


2021-12-03 12:57:26,013 - INFO - Sending a PUSH DATA -
Verson: 02, Token: 0a0a, Identifier: 00, GatewayEUI: 21cb13cc7a380a3e


2021-12-03 12:57:26,168 - INFO - Receiving a PUSH ACK -
Version: 02, Token: 0a0a, Identifier: 01


2021-12-03 12:57:28,169 - INFO - No response is received from remote servers
````

The JoinAccept packet is not being shown in the LoraWan frame, though the join request is showing. I think the join accept event won't be fired unless the first uplink packet has been received?? 
Now i am able to pull the gateway and send a join request with a join accept ack received but i cannot successfully receive a packet to chirpstack. 

Any suggestions?

![Capture](https://user-images.githubusercontent.com/89781826/144591886-90154f25-db39-4f34-a4ca-560d9c543e6e.PNG)


Also when reviewing device data i see that there is an invalid mic error
````
applicationID:"2"
applicationName:"emulator"
deviceName:"emulatorDevice"
devEUI:"b098c295f6a98191"
type:"UPLINK_MIC"
error:"invalid MIC"
fCnt:0
tags:
publishedAt:"2021-12-03T11:07:45.042618802Z"
````

maybe it is something related to the keys, should I use the -v 1.0.2 attribute?


Also in the documentation is says that the JoinEUI should be set equal to AppEUI in my case i am setting it equal to DevEUI.
Or what does the AppEUI represent because as i know wasn't the AppEUI omitted in the new release of chirpstack?
````
Device:
    JoinEUI: b098c295f6a98191
    DevEUI: b098c295f6a98191
RootKeys:
    AppKey: fe6d154c31a646f585b75d5682f7b67f
    NwkKey: fe6d154c31a646f585b75d5682f7b67f
Gateway:
    GatewayEUI: 21cb13cc7a380a3e
````

**Comment by Xiao-Di** [comment]
Hi,
I notice that u have made PULL procedure and JOIN procedure successfully.
While during the APP procedure, the uplink message is MIC verified by the Chirpstack server and the emulator received a PUSH ACK, but no PUSH RESPONCE was received.
That is mainly because that any DOWNLINK app message(encoded) must be filled in the Chirpstack website so that a PUSH responce could be sent back to the emulator.

**Comment by houluy** [comment]
@hhazime Our latest version has been tested with ChirpStack under **LoRaWAN v1.1**，but version LoRaWAN v1.0.2 is not well examined, there maybe some bugs (especially relevant to MIC calculation since it is complex and ambiguous). The error message implies that the MIC is not equivalent between the emulator and ChirpStack. This may be caused by invalid field of message to calculate the MIC, invalid NwkSKey generated by emulator or issues of little-endian bytes.  We'll focus on the problems of v1.0.2 in the next stage.  

Anyway, it is better to use **LoRaWAN v1.1** to test, and the latest version works well with ChirpStack by our tests.

Any update on v1.0.2 would be notified to you via the issue. Thanks for your support!

**Comment by hhazime** [comment]
I tried LoRaWAN v1.1 & it is working fine, I will use it instead of V1.0.2 for now.

Shall we keep the issue open for later on, do you want me to close it?

Thank you both for your support @houluy @Xiao-Di

**Comment by houluy** [comment]
Glad to hear it! Feel free to contact us if there's any problem using the emulator!

**Comment by hhazime** [comment]
Are you planning to implement downlink capabilities ??? 
Or is there a way to fake the downlink window capabilities and capture the downlink by subscribing to the gateway topic and reading the packet data?

**Comment by houluy** [comment]
@hhazime The MQTT is only used inside the ChirpStack. Do u mean by generate a client and subscribe the MQTT topic of ChirpStack? That's not a function of normal LoRa end devices or gateways. It is better to write an individual program to insert.
